### ISSUE TITLE
Extension times out with Zip Pay

### ISSUE THREAD

**Issue by lsliwaradioluz** [commercetools/commercetools-adyen-integration#936] opened 2022-03-14 14:44 UTC
Hello team,

while using Zip Pay, I am getting the `Extension did not respond in time` error. Usually I would suspect that it's just the `timeoutInMs` set to 2000 instead of 10000ms. However, that's not the case since its value is 10000 already.

What happens before the extension is reached is I'm sending payment update request:

```
  apiClient.execute({
    uri: requestBuilder.payments.byId(paymentId).build(),
    method: 'POST',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
    body: {
      version: 8,
      actions: [
        {
          action: 'setCustomField',
          name: 'submitAdditionalPaymentDetailsRequest',
          value: JSON.stringify({
            details: {
              redirectResult // this one is returned by Zip Pay within request.query
            }
          })
        }
      ]
    }
  });
```

The `redirectResult` string is long, just like this one:

```
{"details":{"redirectResult":"X6XtfGC3!eyJyZWRpcmVjdFBheW1lbnREYXRhIjp7ImFjcXVpcmVyQWNjb3VudElkIjo2MTg5NDAsImFkZGl0aW9uYWxEYXRhIjp7Im9yaWdpbmFsQ2hlY2tvdXRJZCI6ImF1LWNvXzNGU0Q0S2dyMHI1RklUU01jcTN4WkQifSwiYW1vdW50Ijp7ImN1cnJlbmN5IjoiQVVEIiwidmFsdWUiOjE3MDAwfSwiYXBpVmVyc2lvbiI6NjcsImFwcGxpY2F0aW9uSW5mbyI6eyJleHRlcm5hbFBsYXRmb3JtIjp7Im5hbWUiOiJjb21tZXJjZXRvb2xzIiwiaW50ZWdyYXRvciI6ImNvbW1lcmNldG9vbHMgUHJvZmVzc2lvbmFsIFNlcnZpY2VzIn0sIm1lcmNoYW50QXBwbGljYXRpb24iOnsibmFtZSI6ImNvbW1lcmNldG9vbHMtYWR5ZW4taW50ZWdyYXRpb24tZXh0ZW5zaW9uIiwidmVyc2lvbiI6IjkuMC4wIn19LCJicmFuZENvZGUiOiJ6aXAiLCJjaGVja291dENoYW5uZWwiOiJXZWIiLCJjb3VudHJ5Q29kZSI6IkFVIiwibWVyY2hhbnRBY2NvdW50IjoiTGlrZXdpemVBdXN0cmFsaWFQdHlMdGRfT3B0dXNBVS1VQVRfVEVTVCIsIm1lcmNoYW50UmVmZXJlbmNlIjoiOGFkZTI5YjEtYzE3OS00OTBjLWJhY2YtZDc0OWEwODg3NDJjIiwib3JpZ2luYWxQc3BSZWZlcmVuY2UiOiJUTDMyNFczMkI0QkxOSzgyIiwicGFsUmVzdWx0UHNwUmVmZXJlbmNlIjoiTFhUU0tCUkcyM1JaTk44MiIsInJlcXVlc3RBZGRpdGlvbmFsRGF0YSI6eyJhcHBsaWNhdGlvbkluZm8ubWVyY2hhbnRBcHBsaWNhdGlvbk5hbWUiOiJjb21tZXJjZXRvb2xzLWFkeWVuLWludGVncmF0aW9uLWV4dGVuc2lvbiIsImFwcGxpY2F0aW9uSW5mby5leHRlcm5hbFBsYXRmb3JtSW50ZWdyYXRvciI6ImNvbW1lcmNldG9vbHMgUHJvZmVzc2lvbmFsIFNlcnZpY2VzIiwiYWxsb3czRFMyIjoidHJ1ZSIsImFwcGxpY2F0aW9uSW5mby5tZXJjaGFudEFwcGxpY2F0aW9uVmVyc2lvbiI6IjkuMC4wIiwibWVyY2hhbnRJbnRlZ3JhdGlvbi52ZXJzaW9uIjoiNjciLCJhcHBsaWNhdGlvbkluZm8uZXh0ZXJuYWxQbGF0Zm9ybU5hbWUiOiJjb21tZXJjZXRvb2xzIiwibWVyY2hhbnRJbnRlZ3JhdGlvbi50eXBlIjoiQ0hFQ0tPVVRfR0VORVJJQyJ9LCJyZXR1cm5VcmwiOiJodHRwczpcL1wvY2hlY2tvdXRzaG9wcGVyLXRlc3QuYWR5ZW4uY29tXC9jaGVja291dHNob3BwZXJcL2NoZWNrb3V0UGF5bWVudFJldHVybj9ncGlkPUdQRDBCNjFFMzJBNkFBOTAwNyIsInNlbGVjdGVkQnJhbmQiOiJ6aXBfQVUiLCJzaG9wcGVyTG9jYWxlIjoiZW4tQVUiLCJza2luQ29kZSI6InB1Yi52Mi44MjE2MzA2MzI4NzAxNjU2Lk1McEZhRkNFN2hfSVcxNkQwdWpGZldySEFHMGZFWDhkamFQNTRhVjRtcm8ifSwicmV0dXJuVXJsUGFyYW1zIjp7InJlc3VsdCI6ImFwcHJvdmVkIiwiY2hlY2tvdXRJZCI6ImF1LWNvXzNGU0Q0S2dyMHI1RklUU01jcTN4WkQifX0=TGGATec5dEUs+1Puz7qATJSBOlxGZxL2KKHmEzceMd4="}}
```

Funnily enough, there are no errors in the Adyen API Logs or in the extension logs itself. It's just the extension connection that times out. My initial thought was to increase the timeoutInMs to something like 12s but I guess that's not the right approach.

My extension has been deployed using the `commercetools/commercetools-adyen-integration-extension:v9.0.2` docker image. It runs within the same container as the app using it. The Commercetools region matches the GCP cluster containing the extension and the app.

I don't even know where to start. Do you guys have any hints on why this might be happening? 

For good measure, I attach a file containing logs from the extension (only the ones referring to the failing transaction).

[extension-logs.log](https://github.com/commercetools/commercetools-adyen-integration/files/8245923/extension-logs.log)

**Comment by ahmetoz** [comment] 2022-03-15 14:06
Hey @lsliwaradioluz 

> I am getting the Extension did not respond in time error. 

As you mentioned this issue comes from the commercetools api extension, if the extension module could not response in time. 

> My initial thought was to increase the timeoutInMs to something like 12s but I guess that's not the right approach.

Yes, 10s should be enough for most of the cases.

>I attach a file containing logs from the extension (only the ones referring to the failing transaction).

According to logs I could see there is a response (submitAdditionalPaymentDetailsResponse) but for your case the api extension already timed out, and actions can not be saved to payment, which shows that the code works but network is slow (request seems logged at "2022-03-09T11:38:32.323Z", and response logged at "2022-03-09T11:38:44.069Z" so bigger than 10s already).

In general we can not do much in terms of making the request/response flow faster if it's the real root cause, so I would suggest reaching the Adyen support for further investigation as they could see the details better than us.

Some hints from my side for your investigation: 
- There might be some misconfiguration on zippay or Adyen side (I have not tested zippay so can not guess much here)
- Also it might happen because your test environment (network delays or so) is slow to response in 10s.
- Try out the latest release of integration to see if there is a difference.
- Ensure the deployment and it's network is fast enough, there might be some delays there too.

BR, Ahmet.

**Comment by lsliwaradioluz** [comment] 2022-03-16 07:17
Thank you for the tips Ahmet, have a good day!

**Comment by ahmetoz** [comment] 2022-03-22 09:54
Your welcome @lsliwaradioluz 
I'm closing the issue for now, please let us know the details of the issue if you resolved it, also let us know if you see an improvement in the integration that causes timeouts.
BR, Ahmet

**Closed by ahmetoz** 2022-03-22 09:54 UTC
