### ISSUE TITLE
Use of X-Correlation-Id of CT as Idempotency-Key for  Adyen API call ?

### ISSUE THREAD

**Issue by milindsingh** [commercetools/commercetools-adyen-integration#930] opened 2022-02-21 10:20 UTC
As suggested by Adyen to avoid duplicate request on failure, `Idempotency-Key` (a unique request id usually uuid) should sent in the header in each API call from extension.

Why not use the CT event `X-Correlation-Id ` header as  `Idempotency-Key`  for each API call in extension ?

This helps to avoid duplicate refunds.

Please refer to:
https://docs.adyen.com/development-resources/api-idempotency
https://docs.commercetools.com/api/general-concepts#correlation-id

**Comment by lojzatran** [comment] 2022-02-21 10:48
Hi @milindsingh 

Thank you for the suggestion. I will take this topic and discuss internally with the team. I will get back to you once we have an agreement how to approach this.

**Comment by butenkor** [comment] 2022-02-21 19:35
Hi @milindsingh Did extension produced a duplicate request or the issue is hypothetical? In case you hit a real case scenario would you please describe how it can be reproduced?

**Comment by butenkor** [comment] 2022-03-09 14:30
Hi @milindsingh - is it still a topic or the issue can be closed?

**Comment by milindsingh** [comment] 2022-03-09 14:39
This can happen when we do multiple refund.

First refund failure to receive response due network failure or adyen fails to return reponse but got created.

Second refund created, causes all intial state refund to be sent adyen again.

Notification can be delayed.

So finally we have 3 refunds.

**Comment by butenkor** [comment] 2022-03-09 14:54
Thanks for the input. Would it be an option for you to include `Idempotency-Key` in the commercetools payment transactions you add as a custom field? In this case you would be responsible for the uniqueness of the `Idempotency-Key`.

**Comment by milindsingh** [comment] 2022-03-10 05:59
Yes that is something I was planning to do. I have made some changes to my fork and will be testing this week

**Comment by lojzatran** [comment] 2022-09-09 20:30
Hi @milindsingh 

We added idempotency key in these releases: https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.13.0, https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.11.0. Therefore I'm closing this issue. If you have further questions, feel free to reopen or create another issue.

**Closed by lojzatran** 2022-09-09 20:30 UTC
