### ISSUE TITLE
Webhook notification is changing the payment method

### ISSUE THREAD

**Issue by milindsingh** [commercetools/commercetools-adyen-integration#896] opened 2021-12-29 16:43 UTC
CT Payment Method is `paywithgoogle` but on Authorization notification it becomes `visa`. Is this expected behavior ?

```json
{"NotificationRequestItem":{"amount":{"currency":"AUD","value":9900},"eventCode":"AUTHORISATION","eventDate":"2021-12-29T13:57:26+01:00","merchantAccountCode":"AccountECOM","merchantReference":"19000011558_2687","operations":["CANCEL","CAPTURE","REFUND"],"paymentMethod":"visa","pspReference":"883640782646048J","success":"true"}}
```

**Comment by lojzatran** [comment] 2021-12-29 17:28
Hi @milindsingh thanks for the question. We did not test `paywithgoogle` so we are not sure if it is expected behaviour or not. However, we do NOT modify the payment method nor the notification from Adyen, so this looks like a specific behaviour in Adyen. Please contact Adyen with your question and when you get an answer, kindly let us know by commenting this issue.

**Comment by milindsingh** [comment] 2021-12-30 19:38
I have received reply from Adyen, there is currently some issue in test environment and they are fixing it. 
Beside that, is there any difference in `gpay` and `paywithgoogle` type?

> Dear Milind, 
> 
> Thank you for your email. 
> 
> We have had this problem reported in the TEST environment only, and our developers are working on a permanent fix. In the meantime I have added some configurations on your account to receive this properly in the webhook. 
> 
> Could you kindly test this again and let me know if it now works? 
> Happy Holidays! 
> Warm Wishes,
> 
> Adyen Tech Support.

**Comment by lojzatran** [comment] 2022-01-12 11:51
Hi @milindsingh 
Thank you for sharing the reply.

As to your next question, unfortunately it's also Adyen specific and as I wrote before, we did not test any Google payments, so you should ask Adyen support.

**Comment by lojzatran** [comment] 2022-01-17 09:52
Hi @milindsingh 

Do you have other questions to this topic? If not, I will close the issue.

Thank you.

**Comment by lojzatran** [comment] 2022-01-17 09:53
Hi @milindsingh 

Do you have other questions to this topic? If not, I will close the issue.

Thank you.

**Closed** 2022-01-20 12:41 UTC

**Comment by milindsingh** [comment] 2022-03-15 05:51
@lojzatran 
We are now facing a race condition, **Webhook is adding authorize transaction even before submit additional details call happens for 3DS details submit.**
We are using Authorization:Success as condition to not allow any further changes from customer to block any abuse of payment. 
But due to this behavior, it is very difficult to add any validation. 

Can you suggest  how can we handle this ?
