### ISSUE TITLE
Webbook update for Authorization success is updating payment version in nochange case

### ISSUE THREAD

**Issue by milindsingh** [commercetools/commercetools-adyen-integration#874] opened 2021-11-29 13:59 UTC
As suggested in Adyen documentation that authorization may fail in some cases after getting success, I have enabled the webhook for all cases from Adyen account.

The below code does not check transaction for Authorization as transaction type resulting in re-updating transaction and increase payment version in CT.

https://github.com/commercetools/commercetools-adyen-integration/blob/3191374ff818c0e1c36986a6f960e00dce08c014/notification/src/handler/notification/notification.handler.js#L312-L336

I would like to know the fix, either we should keep the authorization webhook disabled or add it to compare ?

**Comment by ahmetoz** [comment] 2021-11-29 14:14
Hey @milindsingh thanks for reporting the issue, 

> As suggested in Adyen documentation that authorization may fail in some cases after getting success, I have enabled the webhook for all cases from Adyen account.

To understand it better may I request you to share the notification payload object's eventCode and success you are getting from Adyen so I could check if the mapping exists for this notification type ?

From our docs:

> Each notification contains an `eventCode` that specifies which type of event triggered the notification.
Notification module maps this `eventCode` and `success` pair to
commercetools [transactionType](https://docs.commercetools.com/http-api-projects-payments#transactiontype)
and [transactionState](https://docs.commercetools.com/http-api-projects-payments#transactionstate).

So, we have a map for each notification type such as: 

https://github.com/commercetools/commercetools-adyen-integration/blob/77f9cbab55efe4ca40761666983d6f3244b35c87/notification/resources/adyen-events.json#L2-L7

**Comment by milindsingh** [comment] 2021-11-29 14:32
Yes, the code is correct but update is still happening. A interaction is added in CT for the update (removed other data).  Please check the following:

Notification Payload:
```json
{
   "live":"false",
   "notificationItems":[
      {
         "NotificationRequestItem":{
            "additionalData":{
               "fraudCheck-25-CVCAuthResultCheck":"0",
               "fraudCheck-75-PaymentDetailCarteBancaireRefCheck":"0",
               "fraudCheck-72-TransactionTimeCheck":"0",
               "refusalReasonRaw":"AUTHORISED",
               "eci":"07",
               "fraudCheck-29-LiabilityShiftCheck":"50",
               "acquirerAccountCode":"TestPmmAcquirerAccount",
               "fraudCheck-63-TransactionAmountCheck":"0",
               "fraudCheck-64-TransactionAmountVelocity":"0",
               "xid":"N\\/A",
               "fraudCheck-52-DistinctPaymentDetailUsageByShopper":"0",
               "threeDAuthenticated":"false",
               "fraudCheck-2-CardChunkUsage":"1",
               "fraudCheck-54-DistinctSharedPaymentDetailUsageByShopper":"0",
               "fraudManualReview":"false",
               "threeDOffered":"true",
               "fraudCheck-3-PaymentDetailUsage":"1",
               "threeDOfferedResponse":"N",
               "authorisationMid":"1000",
               "cavv":"N\\/A",
               "fraudCheck-46-DistinctCountryUsageByShopper":"0",
               "authorisedAmountCurrency":"AUD",
               "threeDAuthenticatedResponse":"N\\/A",
               "threeds2.cardEnrolled":"false",
               "fraudCheck-53-DistinctSharedShopperIpUsageByShopper":"0",
               "avsResultRaw":"4",
               "retry.attempt1.rawResponse":"AUTHORISED",
               "paymentMethod":"visa",
               "fraudCheck-55-ShopperAuthorisedFrequency":"25",
               "fraudCheck-50-DistinctShopperEmailUsageByShopper":"0",
               "fraudCheck-48-ChargebackCountByShopper":"0",
               "avsResult":"4 AVS not supported for this card type",
               "fraudCheck-41-PaymentDetailNonFraudRefCheck":"50",
               "cardSummary":"0000",
               "retry.attempt1.avsResultRaw":"4",
               "networkTxReference":"538395784261353",
               "totalFraudScore":"-162",
               "hmacSignature":"zFxq1Ms1q2voQdW9YWlFqbvdUExD3sNFF501NYbNSMk=",
               "fraudCheck-79-BinAttackRefCheck":"0",
               "expiryDate":"03\\/2030",
               "fraudCheck-15-IssuingCountryReferral":"0",
               "cavvAlgorithm":"N\\/A",
               "fraudCheck-37-ShopperDetailsUsage":"10",
               "fraudCheck-47-BlockedCardsUsageByShopper":"0",
               "cardBin":"498808",
               "cvcResultRaw":"M",
               "fraudCheck-4-HolderNameUsage":"1",
               "fraudCheck-51-DistinctShopperReferenceUsageByShopper":"0",
               "merchantReference":"bd9b684e-de11-4e3a-8ce7-6de2fd47eafd",
               "acquirerReference":"7CBMI6AVDGC",
               "fraudCheck-13-IssuerRefCheck":"0",
               "fraudCheck-10-HolderNameContainsNumber":"0",
               "fraudCheck-70-ShopperConsecutiveRefusalsCheck":"0",
               "cardIssuingCountry":"IN",
               "fraudCheck-69-AutomatedReferralCheck":"0",
               "liabilityShift":"false",
               "fraudResultType":"GREEN",
               "authCode":"070162",
               "cardHolderName":"vikas kalla",
               "isCardCommercial":"unknown",
               "PaymentAccountReference":"WOsH6UfDu6Nsdqxcnslr4AX50Ug5G",
               "retry.attempt1.acquirerAccount":"TestPmmAcquirerAccount",
               "retry.attempt1.acquirer":"TestPmmAcquirer",
               "fraudCheck-78-ShopperBehaviorCheck":"0",
               "fraudCheck-40-ShopperAddressRefCheck":"-100",
               "authorisedAmountValue":"4500",
               "fraudCheck-27-PmOwnerRefCheck":"-100",
               "fraudCheck-11-HolderNameIsOneWord":"0",
               "issuerCountry":"IN",
               "cvcResult":"1 Matches",
               "retry.attempt1.responseCode":"Approved",
               "fraudCheck-71-LoyalShopperTrustCheck":"0",
               "fraudCheck-1-PaymentDetailRefCheck":"-100",
               "fraudCheck-49-DistinctShopperIpUsageByShopper":"0",
               "retry.attempt1.shopperInteraction":"Ecommerce",
               "metadata.ctProjectKey":"cos-au-dev",
               "cardPaymentMethod":"visacommercialpremiumdebit",
               "acquirerCode":"TestPmmAcquirer"
            },
            "amount":{
               "currency":"AUD",
               "value":4500
            },
            "eventCode":"AUTHORISATION",
            "eventDate":"2021-11-29T13:38:50+01:00",
            "merchantAccountCode":"HMAccount249ECOM",
            "merchantReference":"bd9b684e-de11-4e3a-8ce7-6de2fd47eafd",
            "operations":[
               "CANCEL",
               "CAPTURE",
               "REFUND"
            ],
            "paymentMethod":"visa",
            "pspReference":"862638189530218C",
            "reason":"070162:0000:03\\/2030",
            "success":"true"
         }
      }
   ]
}
```


CT Payment:
```json
{
    "id": "bc0529e3-ebf2-493d-b5c1-20d18d9edbb8",
    "version": 13,
    "lastMessageSequenceNumber": 5,
    "createdAt": "2021-11-29T12:36:49.573Z",
    "lastModifiedAt": "2021-11-29T12:38:51.983Z",
    "lastModifiedBy": {
        "clientId": "7GSxP9uCmKVbE13KvJHEPgKh",
        "isPlatformClient": false
    },
    "createdBy": {
        "clientId": "7GSxP9uCmKVbE13KvJHEPgKh",
        "isPlatformClient": false
    },
    "key": "bd9b684e-de11-4e3a-8ce7-6de2fd47eafd",
    "amountPlanned": {
        "type": "centPrecision",
        "currencyCode": "AUD",
        "centAmount": 4500,
        "fractionDigits": 2
    },
    "paymentMethodInfo": {
        "paymentInterface": "ctp-adyen-integration",
        "method": "visa",
        "name": {
            "en": "Credit card visa"
        }
    },
    "custom": {
        "type": {
            "typeId": "type",
            "id": "192ab9a7-5f3e-4c2c-8ed0-33876aa80939"
        },
        "fields": {
            // removed request...
        }
    },
    "paymentStatus": {},
    "transactions": [
        {
            "id": "58a14924-4526-40fe-b10d-4d4aae7b5cf6",
            "type": "Authorization",
            "amount": {
                "type": "centPrecision",
                "currencyCode": "AUD",
                "centAmount": 4500,
                "fractionDigits": 2
            },
            "interactionId": "862638189530218C",
            "state": "Success"
        }
    ],
    "interfaceInteractions": [
        // removed requests...
        {
            "type": {
                "typeId": "type",
                "id": "fdfd2428-ebb5-4dc5-adae-ad37b7b77262"
            },
            "fields": {
                "createdAt": "2021-11-29T12:38:50.970Z",
                "status": "authorisation",
                "type": "notification",
                "notification": "{\"NotificationRequestItem\":{\"amount\":{\"currency\":\"AUD\",\"value\":4500},\"eventCode\":\"AUTHORISATION\",\"eventDate\":\"2021-11-29T13:38:50+01:00\",\"merchantAccountCode\":\"HMAccount249ECOM\",\"merchantReference\":\"bd9b684e-de11-4e3a-8ce7-6de2fd47eafd\",\"operations\":[\"CANCEL\",\"CAPTURE\",\"REFUND\"],\"paymentMethod\":\"visa\",\"pspReference\":\"862638189530218C\",\"success\":\"true\"}}"
            }
        }
    ]
}
```

**Comment by ahmetoz** [comment] 2021-11-29 14:46
> that authorization may fail in some cases after getting success

So in your case you're getting eventCode: "AUTHORISATION" and success=true multiple time, the first statement in the issue that you wrote before confuses me a bit ?

Is the case happening like below ?:  
1- The AUTHORISATION is succeeded and a transaction added with Success state to ct payment.
2- Adyen send a notification with same eventCode and success status, notification module added the notification to ct payment's interface interaction, and also ct payment resource version changed but ct payment transaction state is not changed?

I think in this case we can not do much as keeping the notification interaction in ct payment is reasonable for tracking purposes by notification module's design, normally I expect that adyen sends a notification when something changed on the payment 🤔

**Comment by milindsingh** [comment] 2021-11-29 17:04
@ahmetoz This is default Adyen behavior. Its notifying for authorization success (if enabled). 

But since we already have loaded `payment` from CT shall we not compare the transaction `state` with current Adyen Notification status before doing an update call to CT ?

https://github.com/commercetools/commercetools-adyen-integration/blob/3191374ff818c0e1c36986a6f960e00dce08c014/notification/src/handler/notification/notification.handler.js#L170-L174

**Comment by ahmetoz** [comment] 2021-11-29 17:47
Hey @milindsingh, Sorry, I still did not get the issue you have, if possible it might be helpful to provide a reproducable case otherwise I only have assumptions as below:

Let's assume the payment transaction is created by extension module and the ct payment has a transaction  status `Pending` created when the `makePaymentRequest` is succeeded. 
Then adyen sends first notification asyncronously, again let's assume it's `eventCode='AUTHORISATION' and status= 'success'`. The notification module maps it to ct transaction type, and status `(type=Authorization and status=Success)`. The code snippet that you shared does that with checking if a ct payment transaction exists for this pspReference. In case the transaction exists it checks if the status is same (in the example it's different 'Pending' -> 'Success') so the transaction status is updated also the interface interaction is added for this notification. 
Assume adyen sent another notification after some time with (`eventCode='AUTHORISATION' and status= 'success'`), in this case again the notification module will check the oldTransaction and it's status, and will see the transaction and it's status is up to date, so it will not update the status or type of the transaction. 

As explained before if your concern is related to any update on the ct payment, it's normal because adyen could send any  notification and this will be added as an interface interaction even when the status is same.

Note that code below is checking if the same notification payload exists on the interface interaction, and if the payload does not exists it's added as a new interaction, therefore ct payment is updated and it's version increased.

https://github.com/commercetools/commercetools-adyen-integration/blob/3191374ff818c0e1c36986a6f960e00dce08c014/notification/src/handler/notification/notification.handler.js#L154-L161

**Comment by milindsingh** [comment] 2021-11-30 15:14
My flow is:

1. Merchant Server calls `makePayment`
2. Payment is created in commercetools and an `Authorization` transaction is added with `Success` state (by default).
3. Merchant server receive `makePayment` response with invalid version (due step 4).
4. Webhook Notifies again for `Authorization` with `Success` and updates the payment version as interaction is missing for this.

My understanding is why update transaction from notification if its already have same state i.e. `Authorization=Success`

The issue I face is that due step 4 is happening after I receive response in step 3,  making the payment version invalid, and need to make again call to get payment.

**Comment by ahmetoz** [comment] 2021-11-30 15:58
Hey @milindsingh thanks for the update, 

Notification from adyen is an async process, it's not known in code when a notification is received, in your flow, an interface interaction will be added and payment version is changed because of the update on ct payment object.

I would consider refetching before doing an update to payment, also you could implement an exception handler for the (http 409 status // ConcurrentModification), therefore when the response status is 409, you might refetch the payment object and calculate the update actions again. (I assume you are trying to update the payment object after a successful transaction).

Beside that I will consult the team for their opinion for the issue/thread and will update here if could do sth about this.

**Comment by ahmetoz** [comment] 2021-11-30 18:37
Hey @milindsingh one of my team members said, does it help ?

> I wonder why they need to update the payment right after makePayment request since it might be not necessary? Alternatively they could provide that value to payment object before makePayment request so that they do need to update afterwards.

**Comment by milindsingh** [comment] 2021-11-30 18:45
Thanks @ahmetoz  that is correct, but we utilising makePaymentResponse additionalData for some other services, and then updating custom fields on payment.

**Comment by ahmetoz** [comment] 2021-12-01 07:58
Hey @milindsingh, it seems you have couple of options here but I could not see an action from our side, as said before notification handler is generic for all notification types.

- refetch ct payment object before doing an update
- handle 409 (which is also a good practice in general to retry with exponential backoff on http status 409)
- configure Adyen webhook to not get 'Authorization' notification (in this case I could not suggest it as there might be different scenarios or edge cases on notifications)

Please let me know if I'm missing sth.

**Comment by ahmetoz** [comment] 2021-12-08 11:53
Hey @milindsingh, did you find a solution for your case ? Let me know if you need further support.

**Comment by ahmetoz** [comment] 2021-12-17 12:26
I'm closing the issue for now, please feel free to reopen in case of open questions.

**Closed by ahmetoz** 2021-12-17 12:26 UTC

**Comment by milindsingh** [comment] 2022-03-15 05:51
@lojzatran
We are now facing a race condition, **Webhook is adding authorize transaction even before submit additional details call happens for 3DS details submit.**
We are using `Authorization:Success` as condition to not allow any further changes from customer to block any abuse of payment.
But due to this behavior, it is very difficult to add any validation.

Can you suggest how can we handle this ?

**Comment by lojzatran** [comment] 2022-03-15 08:36
Hi @milindsingh 

We add an authorize transaction only when the response from Adyen has 'Authorize' result code (https://github.com/commercetools/commercetools-adyen-integration/blob/27b4405faa50091cde366c8b45c7eaa70f5d1034/extension/src/paymentHandler/payment-utils.js#L120). Maybe in your case, the payment was already authorized and there was no need to do submit additional details. Does the authorize transaction have interactionId?
