### ISSUE TITLE
is affirm payment method supported? 

### ISSUE THREAD

**Issue by manju613** [commercetools/commercetools-adyen-integration#671] opened 2021-04-27 16:17 UTC
Hi, 

May I know affirm payment method is supported by this module? 

Also, if it supports - could you please provide sample json makepayment request for testing. 

Thanks in advance!

**Comment by butenkor** [comment] 2021-04-28 08:53
Hello @manju613 as stated in the integration description we support all the payment methods which are available as Adyen Web Component. Since Affirm is also available as [web-component](https://docs.adyen.com/online-payments/supported-payment-methods) you can follow the frontend integration guide here: https://docs.adyen.com/payment-methods/affirm/web-component#make-a-payment and supply to the integration (through commercetools) the generated make payment request as documented. Let us know if something is not clear so that we can improve our documentation.

**Comment by butenkor** [comment] 2021-05-05 09:41
Hello @manju613 Do you have any other questions or the issue can be closed?

**Comment by manju613** [comment] 2021-06-01 13:47
Is this the valid JSO request for Affirm .. Please confirm.

{
  "amountPlanned": {
    "currencyCode": "USD",
    "centAmount": 1000
  },
  "paymentMethodInfo": {
    "paymentInterface": "ctp-adyen-integration"
  },
  "custom": {
    "type": {
      "typeId": "type",
      "key": "ctp-adyen-integration-web-components-payment-type"
    },
    "fields": {
    "cartIdReference":"ec345239-b4d5-4270-9f1f-4a37340d29aa",
      "adyenMerchantAccount": "NirmanECOM",
      "commercetoolsProjectKey": "breville-dev",
      "makePaymentRequest": "{\"merchantAccount\":\"NirmanECOM\",\"countryCode\":\"US\",\"amount\":{\"currency\":\"USD\",\"value\": 1000},\"shopperReference\":\"Referenceshopper10001\",\"reference\":\"10001\",\"channel\": \"Web\",\"paymentMethod\": {\"type\": \"affirm\"  },\"shopperName\": {\"firstName\": \"Simon\",\"lastName\": \"Hopper\"},\"telephoneNumber\": \"+12121234567\",\"shopperEmail\": \"s.hopper@example.com\",\"billingAddress\": {\"city\": \"San Francisco\",\"country\": \"US\",\"houseNumberOrName\": \"274\",\"postalCode\": \"94107\",\"stateOrProvince\": \"CA\",\"street\": \"Brannan St.\"},\"deliveryAddress\": {\"city\": \"San Francisco\",\"country\": \"US\",\"houseNumberOrName\": \"274\",\"postalCode\": \"94107\",\"stateOrProvince\": \"CA\",\"street\": \"Brannan St.\"},\"returnUrl\":\"https://your-company.com/checkout?shopperOrder=12xy..\",\"lineItems\":[{\"quantity\": \"1\",\"amountExcludingTax\": \"331\",\"description\": \"Shoes\",\"id\": \"Item #1\",\"taxAmount\": \"69\",\"productUrl\": \"https://your-company.com/item1/\",\"imageUrl\": \"https://your-company.com/item1.jpg\"},{\"quantity\": \"2\",\"amountExcludingTax\": \"248\",\"description\": \"Socks\",\"id\": \"Item #2\",\"taxAmount\": \"52\",\"productUrl\": \"https://your-company.com/item2/\",\"imageUrl\": \"https://your-company.com/item2.jpg\"}]}"
}
}
}

**Comment by butenkor** [comment] 2021-06-09 12:51
As said, by design the integration is payment method agnostic and supports all Adyen web-components based payments but it does not mean that we have tested all the available payment methods since also new methods are constantly added by the Adyen. 

On the first sight you request seems fine besides the fact that it is not clear why you would put `cartIdReference` to the payment since you always have a native link/reference to the cart once you have created a payment and set it as the payment info: https://docs.commercetools.com/api/projects/carts#add-payment on the cart.

Do you get any particular errors that prevents you from finishing the payment with the integration and Affirm payment method?

**Comment by ahmetoz** [comment] 2021-12-08 11:51
Hey @manju613 sorry for the late reply here. 

Starting from [version 9.1.0](https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.1.0) the integration supports affirm payment, therefore I'm closing the issue, feel free to reopen, if you're experiencing the same issues on your checkout flow 🙏🏽

**Closed by ahmetoz** 2021-12-08 11:51 UTC
