### ISSUE TITLE
Better error handling in API Extension

### ISSUE THREAD

**Issue by wiktor-obrebski** [commercetools/commercetools-adyen-integration#797] opened 2021-08-10 16:45 UTC
Currently after call adyen, the response is always treated as JSON, whatever it's `200` or an error status code:
https://github.com/commercetools/commercetools-adyen-integration/blob/c40cf0b0c7d43f87de3c59a554956109cf6d1ced/extension/src/service/web-component-service.js#L125-L126

But for not-success status codes Adyen do not return JSON, it's return a string, e.g. for 400 response I got `000 Resource not found` in the body.

The extension trying to parse it, but as it's not proper JSON, it fails. But it do not log what's happens, it just log a not really clear error: `invalid json response body at https://checkout-test.adyen.com/vXX/payments/paymentMethods reason: Unexpected number in JSON at position 1`.

It would be nice if you can handle such cases and forward error from Adyen. currently it's hard to debug what's going on in the system.

**Comment by lojzatran** [comment] 2021-08-11 13:27
Hi @wiktor-obrebski 
Thank you for reporting the issue. I checked the documentation and the code, but I cannot reproduce the issue you are reporting.

In [the documentation of Adyen](https://docs.adyen.com/development-resources/error-codes) there are lots of error codes, but when these errors come, they are in JSON format and the code does not fail. Can you tell us exactly what is the use case you had that it returns 400 error with no JSON? We would like to test it first to clarify the root cause of the problem.

**Comment by wiktor-obrebski** [comment] 2021-08-17 16:43
1. Invalid API Key provided, Adyen response:
> errorType=security&errorCode=000&message=HTTP+Status+Response+-+Unauthorized&status=401
2. Proper API Key, but invalid base url, e.g.
send POST to `https://checkout-test.adyen.com/v67/payments2` with valid `X-API-KEY` header.
Adyen response:
> 000 Service payments2 not present

I guess there is more than this. I understand that there are configuration problems, but still - it's one of first problems that developer can met using the library (at least I did). without proper feedback it's hard to realize what's going on.

**Comment by ahmetoz** [comment] 2021-08-19 16:32
Hey @wiktor-obrebski thanks for the feedback and detailed reply here, we will check and try to improve the error handling as much as possible 🙏🏽

**Comment by ahmetoz** [comment] 2021-08-20 09:26
Hey @wiktor-obrebski I tested on code that responses returned as json body, I wonder how are you running the code. 

The response we are asking is json. Would be nice to know your setup to dig in the issue more.

https://github.com/commercetools/commercetools-adyen-integration/blob/40e7b6e8235d922ab1b603f1b3e6e9ff8e9203ff/extension/src/service/web-component-service.js#L144-L146

**Comment by wiktor-obrebski** [comment] 2021-08-20 17:04
Adyen sometimes ignore the header clearly.
try a request similar to this:
```
curl -X POST -H "X-API-KEY:{REAL_API_KEY}" -H "Content-type":"application/json" https://checkout-test.adyen.com/v67/payments2

**Comment by ahmetoz** [comment] 2021-09-09 08:35
Hey @wiktor-obrebski,

I checked again and I could not find an issue from my investigation. I could add a status check before the calling the .json method of response object. but on my tests for error cases it's returning json, so in the end I need to call the json method. 

If you have a suggestion on the code level to handle the errors I would like to listen, otherwise I would like to close the issue and open it when it occurs for the real scenarios.

**Closed** 2021-09-24 10:02 UTC
